INSERT INTO Item (name, category, barcode, stor_id, size)
VALUES 
('APPLES_Alkmene','fruits','3000',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_Aurora/Southern Rose','fruits','3001',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_Cantared','fruits','3002',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_DEstivale','fruits','3003',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_Discovery','fruits','3004',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_Golden Delicious Blush','fruits','3005',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_Ingrid Marie','fruits','3006',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_Lochbuie','fruits','3007',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_Rubinette','fruits','3008',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_Russet','fruits','3009',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_Cripps Red','fruits','3010',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_Worcester','fruits','3011',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('PEARS_Abate Fetel','fruits','3012',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('PEARS_Beurre Hardy','fruits','3013',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('PEARS_Bon Rouge','fruits','3014',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('PEARS_Clara Friis','fruits','3015',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('PEARS_Concorde','fruits','3016',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('PEARS_Conference','fruits','3017',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('PEARS_Durondeau','fruits','3018',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('PEARS_Flamingo','fruits','3019',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('PEARS_General Leclerc','fruits','3020',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('PEARS_Guyot','fruits','3021',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('PEARS_Josephine','fruits','3022',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('PEARS_Passe Crassane','fruits','3023',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('PEARS_Rocha','fruits','3024',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('PEARS_Rosemarie','fruits','3025',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('PEARS_Triumph de Vienne','fruits','3026',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('ORANGES_Shamouti','fruits','3027',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('ORANGES_Delta Seedless','fruits','3028',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('TANGERINES/MANDARINS_Satsuma','fruits','3029',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('TANGERINES/MANDARINS_Nova (includes Clemenvilla, Suntina)','fruits','3030',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('TANGERINES/MANDARINS_Jamaican Tangor (includes Ortanique, Mandor, Mandora, Tambor, Topaz, Ortanline)','fruits','3031',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('TANGERINES/MANDARINS_Ellendale','fruits','3032',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('MELON_Charentais','fruits','3033',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('MELON_Charentais','fruits','3034',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('NECTARINE_White Flesh, Tree Ripened, Ready-to-eat','fruits','3035',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('ORANGES_Midknight','fruits','3036',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('PINEAPPLE_Queen','fruits','3037',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('PASSION FRUIT_Granadilla, Orange','fruits','3038',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('PHYSALIS/CAPE GOOSEBERRY/GROUND CHERRY_','fruits','3039',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('PITAHAYA_Red (skin color)','fruits','3040',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('RAMBUTAN_','fruits','3041',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('MANGOSTEEN_','fruits','3042',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('GRAPES_Italia, Seeded','fruits','3043',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APRICOTS_Black Velvet','fruits','3044',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('DATES_Fresh, On Branch','fruits','3045',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('DATES_Fresh, Frozen','fruits','3046',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('DATES_Medjool','fruits','3047',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('BEANS_Helda/Flat','vegetables','3048',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('BEANS_Fine','vegetables','3049',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('CABBAGE_Dutch White/Winter White','vegetables','3050',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('CABBAGE_Spring Cabbage/Spring Greens','vegetables','3051',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('GARLIC_String','vegetables','3052',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('PARSNIP_Baby','vegetables','3053',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('PEPPERS (CAPSICUMS)_Elongated (Clovis Red/Lamuyo Red)','vegetables','3054',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('PEPPERS (CAPSICUMS)_Elongated (Clovis Green/Lamuyo Green)','vegetables','3055',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('PEPPERS (CAPSICUMS)_Elongated (Clovis Yellow/Lamuyo Yellow)','vegetables','3056',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('PEPPERS (CAPSICUMS)_Elongated (Clovis Orange/Lamuyo Orange)','vegetables','3057',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('PEPPERS (CAPSICUMS)_Elongated (Clovis White/Lamuyo White)','vegetables','3058',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('SQUASH_Crown Prince','vegetables','3059',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('SQUASH_Vegetable Marrow','vegetables','3060',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('TOMATOES_Beef/Beefsteak','vegetables','3061',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('BAY LEAVES_','herbs','3062',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('FENNEL LEAVES_','herbs','3063',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('ALOE VERA LEAVES_','herbs','3064',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_Cameo','fruits','3065',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_Cameo','fruits','3066',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_Swiss Gourmet','fruits','3067',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_Swiss Gourmet','fruits','3068',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_Gravenstein, Red','fruits','3069',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_Gravenstein, Red','fruits','3070',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_Granny Smith, Red','fruits','3071',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_Lady','fruits','3072',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_Macoun','fruits','3073',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_Greening (RI)','fruits','3074',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_Baldwin','fruits','3075',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_Melrose','fruits','3076',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_Northern Spy','fruits','3077',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_Liberty','fruits','3078',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('ASPARAGUS_Purple','vegetables','3079',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('AVOCADOS_Pinkerton','fruits','3080',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('BERRIES_Saskatoon','fruits','3081',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('BROCCOLI_Crowns','vegetables','3082',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('BRUSSELS SPROUTS_Stalk','vegetables','3083',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('CHERVIL_','herbs','3084',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('CORN_Indian, Decorative','vegetables','3085',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('CORN_Indian. Decorative','vegetables','3086',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('CORN_Indian, Strawberry','vegetables','3087',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('CURRANTS_Red','fruits','3088',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('EGGPLANT (AUBERGINE)_Chinese','vegetables','3089',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('EGGPLANT (AUBERGINE)_Thai','vegetables','3090',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('GOBO ROOT/BURDOCK_','vegetables','3091',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('GRAPEFRUIT_OroBlanco/Sweetie','fruits','3092',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('KALE_Multicolor','vegetables','3095',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('KOHLRABI_Purple/Red/All Other Colors','vegetables','3096',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('LETTUCE_Romaine, Red','vegetables','3097',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('LETTUCE_Boston, Red','vegetables','3098',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('LOTUS ROOT_','vegetables','3099',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('MELON_Gold Honeydew','fruits','3100',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('MELON_Piel de Sapo','fruits','3101',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('MUSHROOMS_Morel','vegetables','3102',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('MUSHROOMS_Enoki','vegetables','3103',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_RoHo 3615','fruits','3104',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('CASHEWS_','nuts','3105',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('MACADAMIA_','nuts','3106',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('ORANGES_Navel','fruits','3107',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('ORANGES_Valencia','fruits','3108',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('ORANGES_Seville (Marmalade type)','fruits','3109',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('ORANGES_Navel, Cara Cara (Red)','fruits','3110',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('PAPAYA/PAWPAW_Red-Fleshed (Solo Sunrise)','fruits','3111',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('PAPAYA/PAWPAW_Meridol','fruits','3112',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('PEACHES_Flat White Flesh (Saturn type)','fruits','3113',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('MANGO_Green','fruits','3114',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('PEACHES_Flat Yellow Flesh','fruits','3115',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('PEACHES_Yellow Flesh (Tree Ripened/Ready-to-eat)','fruits','3116',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('PEACHES_Yellow Flesh (Tree Ripened/Ready-to-eat)','fruits','3117',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('PEARS_Starkrimson','fruits','3118',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('PEPPERS (CAPSICUMS)_Bell, Greenhouse - Green','vegetables','3119',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('PEPPERS (CAPSICUMS)_Bell, Greenhouse - Green','vegetables','3120',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('PEPPERS (CAPSICUMS)_Bell, Greenhouse - Orange','vegetables','3121',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('PEPPERS (CAPSICUMS)_Bell, Greenhouse - White','vegetables','3122',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('PEPPERS (CAPSICUMS)_Bell, Greenhouse - Brown','vegetables','3123',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('PEPPERS (CAPSICUMS)_Bell, Greenhouse - Purple','vegetables','3124',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('PEPPERS (CAPSICUMS)_Habanero','vegetables','3125',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('POMEGRANATE_','fruits','3127',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('POTATO_Purple','vegetables','3128',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('GRAPEFRUIT_Pummelo - Red','fruits','3129',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('PUMPKIN_Jumbo','vegetables','3130',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('PUMPKIN_Decorative (Painted)','vegetables','3131',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('PUMPKIN_White','vegetables','3132',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('PUMPKIN_White - Mini','vegetables','3133',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('PUMPKIN_Pie Pumpkin','vegetables','3134',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('GOURD_Ornamental','vegetables','3135',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('SAPODILLO/NISPERO_','fruits','3136',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('SAPOTE_White','fruits','3137',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('SAPOTE_Black','fruits','3138',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('SAVORY_','herbs','3139',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('SQUASH_Cucuzza','vegetables','3140',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('SQUASH_Opo','vegetables','3141',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('SQUASH_Carnival','vegetables','3142',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('SQUASH_Acorn - baby','vegetables','3143',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('TANGERINES/MANDARINS_Fall Glo','fruits','3144',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('TOMATOES_Plum/Italian/Saladette/Roma (Yellow)','vegetables','3145',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('TOMATOES_Cherry - Red, On the Vine','vegetables','3146',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('TOMATOES_Cherry - Yellow, On the Vine','vegetables','3147',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('TOMATOES_Regular - Yelllow, On the Vine (Truss)','vegetables','3148',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('TOMATOES_Regular - Orange, On the Vine','vegetables','3149',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('TOMATOES_Cocktail/Intermediate - Red','vegetables','3150',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('TOMATOES_Vine Ripe, Regular - Red','vegetables','3151',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('GRAPEFRUIT_Melogold','fruits','3152',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('ORANGES_Delta Seedless','fruits','3153',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('ORANGES_Delta Seedless','fruits','3154',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('ORANGES_Midknight','fruits','3155',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('ORANGES_Midknight','fruits','3156',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('GRAPEFRUIT_White','fruits','3157',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('GRAPEFRUIT_White','fruits','3158',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('GRAPEFRUIT_White','fruits','3159',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('GAI LAN_Synonymous with Chinese Broccoli','vegetables','3160',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('GAI (GUI) CHOY (CHINESE or INDIAN MUSTARD)_Baby - Chinese or Indian Mustard','vegetables','3161',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('ONG CHOY_Synonymous with Water Spinach','vegetables','3162',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('BOK CHOY (PAK CHOI)_Shanghai','vegetables','3163',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('YU CHOY_','vegetables','3164',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('RADICCHIO_Treviso','vegetables','3165',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('CABBAGE_Tuscan','vegetables','3166',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('FRISEE_','vegetables','3167',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('RADICCHIO_Castlefranco','vegetables','3168',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('LETTUCE_Catalogna','vegetables','3169',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_Virginia Gold','fruits','3271',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_Sommerfeld','fruits','3272',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('BEETS_Golden','vegetables','3273',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('PRUNES_Fresh','fruits','3274',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('NAME_Yellow (nyAH-may)','vegetables','3275',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('NAME_White (nyAH-may)','vegetables','3276',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('BROCCOLI_Baby','vegetables','3277',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('PLUMCOT (INTERSPECIFIC PLUM)_','fruits','3278',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('KIWIFRUIT_Golden','fruits','3279',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('KIWIFRUIT_Regular','fruits','3280',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('MELON_Watermelon - Orange, Seedless','fruits','3281',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('TOMATOES_Plum/Italian/Saladette/Roma on the vine - Red','vegetables','3282',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_Honeycrisp','fruits','3283',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_Red Delicious','fruits','3284',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_Golden Delicious','fruits','3285',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('ONIONS_Sweet red Italian - flat','vegetables','3286',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('BANANAS_Hawaiian plantain','fruits','3287',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('MELON_Sprite','fruits','3289',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_Aurora/Southern Rose','fruits','3290',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_Boskoop/Belle de Boskoop','fruits','3291',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_Boskoop/Belle de Boskoop','fruits','3292',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_Scifresh','fruits','3293',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_Scifresh','fruits','3294',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_Sciearly','fruits','3295',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_Sciearly','fruits','3296',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_Scired','fruits','3297',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_Redfield','fruits','3298',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_Sonya','fruits','3299',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_Sonya','fruits','3300',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_Cripps Red','fruits','3301',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APRICOTS_Regular','fruits','3302',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('BABACO_','fruits','3303',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('BERRIES_Loganberries','fruits','3304',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('CURRANTS_Black','fruits','3305',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('MELON_Charentais','fruits','3306',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('MELON_Charentais','fruits','3307',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('MELON_Watermelon - Orange, Seedless','fruits','3308',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('ORANGES_Lima','fruits','3309',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('ORANGES_Pera','fruits','3310',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('PASSION FRUIT_Curuba/Banana','fruits','3311',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('PASSION FRUIT_Granadilla - Yellow/Maracuja','fruits','3312',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('PEACHES_White Flesh - Tree Ripened/ Ready-to-eat','fruits','3313',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('PEACHES_White Flesh - Tree Ripened/ Ready-to-eat','fruits','3314',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_Scilate','fruits','3315',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('PEARS_Carmen','fruits','3316',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('PEARS_Angelys','fruits','3317',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('PEARS_Passe Crassane','fruits','3318',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('PITAHAYA_Yellow (skin color)','fruits','3319',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('CAULIFLOWER_Romanesco/Broccoflower/Caulibroc','vegetables','3320',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('CELERY ROOT/CELERIAC_With leaves attached','vegetables','3321',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('CHOY SUM/PAK CHOI SUM_','vegetables','3322',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('CHOY SUM/PAK CHOI SUM_Baby','vegetables','3323',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('ESCAROLE/BATAVIAN CHICORY_Red','vegetables','3324',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('LETTUCE_Lollo Bionda/Coral - Green','vegetables','3325',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('LETTUCE_Lollo Rossa/Coral - Red','vegetables','3326',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('LETTUCE_Mignonette (Compact red-tinged butterhead varieties)','vegetables','3327',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('LETTUCE_Mixed small-leaf salad (eg Sucrine, Mesclun, Rocket/Arugula)','vegetables','3328',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('LETTUCE_Oak Leaf - Green','vegetables','3329',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('LETTUCE_Oak Leaf - Reg','vegetables','3330',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('ONIONS_Red Fresh - Bunch','vegetables','3331',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('SPINACH_Baby','vegetables','3332',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('SWEET POTATO/YAM/KUMARA_Red/Orangy White Flesh','vegetables','3333',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('SWEET POTATO/YAM/KUMARA_Red/Orangy White Flesh','vegetables','3334',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('TOMATOES_Cocktail/Intermediate - Red/On the Vine (Truss)','vegetables','3335',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('TOMATOES_Cocktail/Intermediate - Red/Plum/Italian/Saladette/Roma/On the Vine (Truss)','vegetables','3336',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('FIGS_(Dried Fruit)','dried fruits','3337',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('ANISE_','herbs','3338',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_Belchard - Chantecler','fruits','3339',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_Bertanne/Golden Russet','fruits','3340',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_Charles Ross','fruits','3341',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_Delblush','fruits','3342',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_Dessert','fruits','3343',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_Gloster','fruits','3344',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_Gloster','fruits','3345',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_Holstein','fruits','3346',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_Laxtons Fortune','fruits','3347',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_Lord Lambourne','fruits','3348',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_Michaelmas Red','fruits','3349',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_Reine des Reinettes/King of the Pippins','fruits','3350',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_Reine des Reinettes/King of the Pippins','fruits','3351',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_Reinettes and Heritage varieties - (incl Canada blanc Reinette du Mans, Armorique/du Vigan/Calville','fruits','3352',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_St Edmunds Pippin','fruits','3353',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('AVOCADOS_Ripe/Ready-to-Eat','fruits','3354',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('BERRIES_Strawberries - Nominal 500g/1 litre','fruits','3355',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('BERRIES_Strawberries - Nominal250g/1/2 litre','fruits','3356',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('CHERRIES_Regular/Red/Black','fruits','3357',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('CHERRIES_Regular/Red/Black','fruits','3358',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('GRAPES_Chasselas','fruits','3359',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('GRAPES_Muscat de Hambourg','fruits','3360',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('GRAPEFRUIT_Without p/harvest treatment','fruits','3361',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('LEMONS_Without postharvest treatment','fruits','3362',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('MANGO_Kensington Pride','fruits','3363',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('MANGO_R2E2','fruits','3364',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('MANGO_Ripe/Ready-to-Eat','fruits','3365',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('MADROÑA_','fruits','3366',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('MELON_Glasshouse - Netted varieties','fruits','3367',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('MELON_Ogen','fruits','3368',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('NECTARINE_Nectavigne (Red Flesh)','fruits','3369',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('ORANGES_Maltaise','fruits','3370',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('ORANGES_Salustiana','fruits','3371',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('ORANGES_Navelate (and other late Navel varieties)','fruits','3372',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('ORANGES_Navelina (incl. Newhall)','fruits','3373',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('ORANGES_Without postharvest treatment','fruits','3374',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('PEACHES_de Vigne & Sanguine (Red Flesh)','fruits','3375',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('PEARS_Alexander Lucas','fruits','3376',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('PEARS_Louise Bonne','fruits','3377',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('PEARS_Santa Maria','fruits','3378',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('PINEAPPLE_Mini','fruits','3379',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('PINEAPPLE_Perola','fruits','3380',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('SOURSOP_','fruits','3381',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('SUGAR APPLE_','fruits','3382',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('TANGERINES/MANDARINS_Clementine','fruits','3383',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('TANGERINES/MANDARINS_Clementine','fruits','3384',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('TANGERINES/MANDARINS_Clementine','fruits','3385',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('TANGERINES/MANDARINS_Clementine (With leaves attached)','fruits','3386',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('TANGERINES/MANDARINS_Clementine (Without p/harvest treatment)','fruits','3387',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('TANGERINES/MANDARINS_Satsuma -Clauselina','fruits','3388',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('TANGERINES/MANDARINS_Satsuma','fruits','3389',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('ARRACACH_','vegetables','3390',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('ARTICHOKES_Rouge Salambo (Red)','vegetables','3391',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('ASPARAGUS_Green - Bunch','vegetables','3392',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('ASPARAGUS_White - Bunch','vegetables','3393',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('ASPARAGUS_Purple - Bunch','vegetables','3394',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('BELGIAN ENDIVE (WITLOOF CHICORY)_Red','vegetables','3395',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('CABBAGE_Savoy, Red','vegetables','3396',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('CABBAGE_Summer Cabbage - Pointed type','vegetables','3397',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('CHICKPEAS_Chickpeas/Garbanzo','vegetables','3398',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('GARLIC_Regular - Fresh/Semi-dried with leaves attached','vegetables','3399',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('GARLIC_Regular - Smoked','vegetables','3400',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('GARLIC_One-clove types','vegetables','3401',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('LEEKS_Regular - Bunch','vegetables','3402',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('LEEKS_Baby - Bunch','vegetables','3403',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('MUSHROOMS_Cep','vegetables','3404',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('MUSHROOMS_Fairy Ring Champignon','vegetables','3405',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('MUSHROOMS_Grey - Tricholoma','vegetables','3406',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('MUSHROOMS_Grisette','vegetables','3407',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('MUSHROOMS_Horn of Plenty/Black Trumpet','vegetables','3408',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('MUSHROOMS_Pioppino','vegetables','3409',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('MUSHROOMS_Saffron Milk-Cap','vegetables','3410',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('MUSHROOMS_Sheep Polypore','vegetables','3411',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('ONIONS_Yellow/Brown Fresh - Bunch','vegetables','3412',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('PEPPERS (CAPSICUMS)_Tabasco','vegetables','3413',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('POTATO_Baking - White','vegetables','3414',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('POTATO_Baking - Red and Red Eye varieties','vegetables','3415',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('RHUBARB_Bunch','vegetables','3416',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('SPINACH_New Zealand Spinach','vegetables','3417',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('SQUASH_Zucchini/Courgette - Round','vegetables','3418',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('BORAGE_','herbs','3419',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('PEARS_Belle du Jumet','fruits','3420',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('MELON_Watermelon - Mini Seedless','fruits','3421',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APRICOTS_InterSpecific','fruits','3422',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('TOMATOES_Heirloom ','vegetables','3423',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('CARROTS_Purple/Red - Beta Sweet','vegetables','3424',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('TANGERINES/MANDARINS_Ellendale','fruits','3425',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('TANGERINES/MANDARINS_Ellendale','fruits','3426',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('TANGERINES/MANDARINS_Ellendale','fruits','3427',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('TANGERINES/MANDARINS_Honey/Murcott','fruits','3428',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('TANGERINES/MANDARINS_Honey/Murcott','fruits','3429',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('TANGERINES/MANDARINS_Honey/Murcott','fruits','3430',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('TANGERINES/MANDARINS_Imperial','fruits','3431',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('TANGERINES/MANDARINS_Imperial','fruits','3432',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('TANGERINES/MANDARINS_Imperial','fruits','3433',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('PEARS_Tosca','fruits','3434',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_Pinova','fruits','3435',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('CAULIFLOWER_Orange','vegetables','3436',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('NECTARINE_Flat Yellow','fruits','3437',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_Ambrosia','fruits','3438',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('NECTARINE_White Flesh Flat','fruits','3439',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('POMEGRANATE_','fruits','3440',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('SQUASH_Butterkin','vegetables','3441',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_New York 1','fruits','3442',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_New York 2','fruits','3443',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_Green Dragon','fruits','3444',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_DS 3','fruits','3445',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('KALE SPROUTS_','vegetables','3446',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_DS 22','fruits','3447',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('CHERRIES_Tip Top','fruits','3448',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('GRAPES_Sugrathirteen','fruits','3449',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('GRAPES_Sugranineteen','fruits','3450',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('GRAPES_Sugrathirtyfour','fruits','3451',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('GRAPES_Sugrathirtyfive','fruits','3452',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('GALANGAL ROOT_','vegetables','3453',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('JACKFRUIT_Green','fruits','3454',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('JACKFRUIT_Yellow','fruits','3455',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('MELON_Winter','fruits','3456',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('PLUMS_President','fruits','3457',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('TOMATOES_Cherry - Orange','vegetables','3458',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('PERSIMMON_Shiny Red','fruits','3459',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_Red Jonaprince','fruits','3460',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_Lady Williams','fruits','3461',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('CHIVES_Garlic/Chinese','herbs','3462',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('Amaranth/Callaloo/Een Choy_','vegetables','3463',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('MANGO_B-74','fruits','3464',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('PEPPERS (CAPSICUMS)_Stripy Bell','vegetables','3465',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('PEARS_Cape Rose','fruits','3466',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_Regal 13-82','fruits','3467',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_Honeycrisp','fruits','3468',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('GRAPES_Sugrasixteen','fruits','3469',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('MELON_Watermelon - Red, Small Seeds','fruits','3470',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('CACTUS LEAVES (Nopales/Cactus Pads)_Baby','vegetables','3471',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('SACRED PEPPER_','herbs','3472',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('EPAZOTE_','herbs','3473',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('SWEET POTATO/YAM/KUMARA_Saffron','vegetables','3474',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('MINT_Peppermint','herbs','3475',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('ORANGE TREE LEAF_','herbs','3476',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('PAPALO_','herbs','3477',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('QUELITES_','vegetables','3478',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('CHIPILIN LEAF_','vegetables','3479',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('PUMPKIN VINE_','vegetables','3480',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('XPELON_','vegetables','3481',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('RABBIT HERB_','herbs','3482',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('PURPLE HERB_','herbs','3483',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_Dalinette','fruits','3484',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('PEARS_Harovin Sundown','fruits','3485',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_CN121','fruits','3486',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_MN 55','fruits','3487',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('MANGO_Red','fruits','3488',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('PEARS_Cepuna','fruits','3489',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_MAIA 1','fruits','3490',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('GRAPES_ARRA FIFTEEN','fruits','3491',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('GRAPES_ARRA TWENTYNINE','fruits','3492',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('ONIONS_Tearless Sweet','vegetables','3493',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('MELON_Watermelon - Yellow Mini Seedless','fruits','3494',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('PEARS_Celina','fruits','3495',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('GRAPES_IFG Core Red Seedless','fruits','3496',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('GRAPES_IFG Core Black Seedless ','fruits','3497',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('GRAPES_IFG Core Green Seedless','fruits','3498',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('GRAPES_IFG Novelty Red Seedless','fruits','3499',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('GRAPES_IFG Novelty Black Seedless','fruits','3500',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('GRAPES_IFG Novelty Green Seedless','fruits','3501',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('GRAPES_ARRA TWENTYSEVEN','fruits','3502',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('GRAPES_ARRA TWENTYEIGHT','fruits','3503',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('GRAPES_ARRA THIRTY','fruits','3504',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('GRAPES_ARRA THIRTYTWO','fruits','3505',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('GRAPES_Sweet Scarlet','fruits','3506',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_WA 38','fruits','3507',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('GRAPES_Thomcord','fruits','3508',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('AVOCADOS_GEM','fruits','3509',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_Ambrosia','fruits','3510',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_WA 2','fruits','3511',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('TOMATOES_Round','vegetables','3512',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_Shinano Gold','fruits','3513',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_Fengapi','fruits','3514',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_PremA 153','ALL','3515',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_PremA 153','fruits','3516',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('PEARS_Oksana','fruits','3518',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_R10-45','fruits','3519',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('ONIONS_SK-20','vegetables','3520',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_Regal D5-100','fruits','3521',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('PEARS_HW624','fruits','3522',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_SQ 159','fruits','3523',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('TANGERINES/MANDARINS_C37','fruits','3524',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_CN121','fruits','3525',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_Howell TC2','fruits','3526',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_Howell TC3','fruits','3527',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_Regal D17-121','fruits','3528',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_PremA 129','fruits','3529',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('GRAPES_Jupiter','fruits','3530',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('GRAPES_Sugra Family Black Seedless','fruits','3531',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('GRAPES_Sugra Family Green Seedless','fruits','3532',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('GRAPES_Sugra Family Novelty Seedless','fruits','3533',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('GRAPES_Sugra Family Red Seedless','fruits','3534',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('ONIONS_Sweetheart','vegetables','3535',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('PLUMS_Sweet Pixie','fruits','3536',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_MAIA-L','fruits','3537',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_Ipador','fruits','3538',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_IFORED Y Series','fruits','3539',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_IFORED R Series','fruits','3540',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_CIVM49','ALL','3541',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_Regal D27-16','ALL','3542',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_Antares','fruits','3600',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_Huaguan','fruits','3601',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_Belgica','fruits','3602',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_Minneiska','fruits','3603',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_Emmons','fruits','3604',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_Nicoter','fruits','3605',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('PEARS_Sweet Sensation','fruits','3606',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_Mariri Red','fruits','3607',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_Sciros','fruits','3608',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('PLUMCOT (INTERSPECIFIC PLUM)_Red','fruits','3609',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('PLUMCOT (INTERSPECIFIC PLUM)_Green','fruits','3610',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('PLUMCOT (INTERSPECIFIC PLUM)_Black','fruits','3611',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_Nicogreen','fruits','3612',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_Fuji Brak','fruits','3613',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APRICOTS_Red','fruits','3614',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_Civni','fruits','3615',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_Scilate','fruits','3616',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('LEMONS_Seedless','fruits','3617',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_Opal','fruits','3618',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_Milwa','fruits','3619',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_Plumac','fruits','3620',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('MANGO_Francis','fruits','3621',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('MELON_Honey Green','fruits','3622',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('MELON_Hami','fruits','3623',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('MELON_Korean','fruits','3624',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_Minnewashta','fruits','3625',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('LEMONS_Meyer','fruits','3626',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_PremA17','fruits','3627',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_PremA280','fruits','3628',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_CIVG198','fruits','3629',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_Co-op 43','fruits','3630',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('PUMPKIN_Pink','vegetables','3631',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('TANGERINES/MANDARINS_Dekopon','fruits','3632',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('BANANAS_Yellow (includes Cavendish)','fruits','4011',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('ORANGES_Navel','fruits','4012',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('ORANGES_Navel','fruits','4013',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('ORANGES_Valencia','fruits','4014',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_Red Delicious','fruits','4015',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_Red Delicious','fruits','4016',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_Granny Smith','fruits','4017',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_Granny Smith','fruits','4018',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_McIntosh','fruits','4019',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_Golden Delicious','fruits','4020',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_Golden Delicious','fruits','4021',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('GRAPES_White/Green Seedless - Peerlette Seedless/Thompson Seedless','fruits','4022',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('GRAPES_Red Seedless - Flame/Ruby/Emperatriz','fruits','4023',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('PEARS_Bartlett/Williams/WBC','fruits','4024',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('PEARS_Anjou','fruits','4025',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('PEARS_Bosc/Beurre Bosc','fruits','4026',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('GRAPEFRUIT_Ruby/Red/Pink (includes Ray Ruby, Ruby, Ruby Red)','fruits','4027',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('BERRIES_Strawberries','fruits','4028',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('PINEAPPLE_','fruits','4029',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('KIWIFRUIT_Regular','fruits','4030',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('MELON_Watermelon - Red   ','fruits','4031',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('MELON_Watermelon - Red, Seedless','fruits','4032',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('LEMONS_','fruits','4033',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('MELON_Honeydew/White Honeydew','fruits','4034',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('NECTARINE_Yellow Flesh','fruits','4035',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('NECTARINE_Yellow Flesh','fruits','4036',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('PEACHES_Yellow Flesh','fruits','4037',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('PEACHES_Yellow Flesh','fruits','4038',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('PLUMS_Black (Includes Ambra, Black Beaut, Prima Black, Blackamber, Black Torch, Catalina, Challenger, Black Diamond, Friar, Royal Diamond, Black Knight, Freedom, Black Flame, Howard Sun, Angeleno)','fruits','4039',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('PLUMS_Black (Includes Ambra, Black Beaut, Prima Black, Blackamber, Black Torch, Catalina, Challenger, Black Diamond, Friar, Royal Diamond, Black Knight, Freedom, Black Flame, Howard Sun, Angeleno)','fruits','4040',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('PLUMS_Red (Includes Santa Rosa, Late Santa Rosa, Red Beaut, Rich Red, Spring Beaut, First Beaut, Royal Red, Red Jewel, Rose Zee, Royal Zee, Ace, Aleta Rose, Burgandy, July Santa Rosa, Frontier, Fortune, Grand Rosa, Red Lane, Red Rosa, Casselman, Autumn Rosa, Mi','fruits','4041',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('PLUMS_Red (Includes Santa Rosa, Late Santa Rosa, Red Beaut, Rich Red, Spring Beaut, First Beaut, Royal Red, Red Jewel, Rose Zee, Royal Zee, Ace, Aleta Rose, Burgandy, July Santa Rosa, Frontier, Fortune, Grand Rosa, Red Lane, Red Rosa, Casselman, Autumn Rosa, Mi','fruits','4042',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('PEACHES_Yellow Flesh - Tree Ripened/Ready-to-eat','fruits','4043',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('PEACHES_Yellow Flesh - Tree Ripened/Ready-to-eat','fruits','4044',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('CHERRIES_Regular/Red/Black','fruits','4045',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('AVOCADOS_Hass','fruits','4046',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('GRAPEFRUIT_Ruby/Red/Pink (Includes Ray Ruby, Ruby, Ruby Red)','fruits','4047',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('LIMES_Regular (incl. Persian, Tahiti & Bearss)','fruits','4048',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('MELON_Cantaloupe/Rockmelon','fruits','4049',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('MELON_Cantaloupe/Rockmelon','fruits','4050',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('MANGO_Red (Includes Tommy Atkins, Kent, Palmer, Vandyke, Edward,Hayden)','fruits','4051',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('PAPAYA/PAWPAW_Regular','fruits','4052',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('LEMONS_','fruits','4053',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('BERRIES_Raspberries - Red','fruits','4054',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('TANGERINES/MANDARINS_','fruits','4055',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('GRAPES_Blue/Black Seedless (All other varieties not listed above including Beauty and Autumn Royal)','fruits','4056',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_Haralson','fruits','4057',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_Haralson','fruits','4058',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('BROCCOLI_','vegetables','4060',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('LETTUCE_Iceberg','vegetables','4061',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('CUCUMBER_Green/Ridge/Short','vegetables','4062',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('TOMATOES_Regular - Red','vegetables','4063',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('TOMATOES_Regular - Red','vegetables','4064',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('PEPPERS (CAPSICUMS)_Bell, Field Grown - Green','vegetables','4065',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('BEANS_Green/French','vegetables','4066',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('SQUASH_Zucchini/Courgette','vegetables','4067',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('ONIONS_Green (Scallions)/Spring','vegetables','4068',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('CABBAGE_Green','vegetables','4069',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('CELERY_Bunch','vegetables','4070',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('CELERY_Bunch','vegetables','4071',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('POTATO_Russet','vegetables','4072',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('POTATO_Red','vegetables','4073',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('SWEET POTATO/YAM/KUMARA_Red/Orangy Red Flesh','vegetables','4074',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('LETTUCE_Red Leaf','vegetables','4075',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('LETTUCE_Green Leaf','vegetables','4076',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('CORN_Sweet Corn, White','vegetables','4077',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('CORN_Sweet Corn, Yellow','vegetables','4078',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('CAULIFLOWER_','vegetables','4079',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('ASPARAGUS_Green','vegetables','4080',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('EGGPLANT (AUBERGINE)_Regular','vegetables','4081',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('ONIONS_Red','vegetables','4082',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('POTATO_White','vegetables','4083',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('ARTICHOKES_','vegetables','4084',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('MUSHROOMS_Regular','vegetables','4085',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('SQUASH_Yellow Zucchini/Gold Bar/Yellow Courgette','vegetables','4086',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('TOMATOES_Plum/Italian/Saladette/Roma - Red','vegetables','4087',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('PEPPERS (CAPSICUMS)_Bell, Field Grown - Red','vegetables','4088',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('RADISH_Bunched Red','vegetables','4089',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('SPINACH_Regular/Bunched','vegetables','4090',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('SWEET POTATO/YAM/KUMARA_White','vegetables','4091',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('PEAS_Chinese Snow Pea/Pea Pod/Mange Tout','vegetables','4092',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('ONIONS_Yellow/Brown','vegetables','4093',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('CARROTS_Bunch','vegetables','4094',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('TURNIP_Yellow','vegetables','4095',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_Ginger Gold','fruits','4096',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_Ginger Gold','fruits','4097',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_Akane','fruits','4098',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_Akane','fruits','4099',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_Fireside','fruits','4100',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_Braeburn','fruits','4101',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_Fireside','fruits','4102',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_Braeburn','fruits','4103',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_Cortland','fruits','4104',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_Cox Orange Pippin','fruits','4105',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_Cortland','fruits','4106',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_Crab','fruits','4107',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_Crispin/Mutsu','fruits','4108',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_Crispin/Mutsu','fruits','4109',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_Crispin/Mutsu','fruits','4110',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_Crispin/Mutsu','fruits','4111',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_Regent','fruits','4112',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_Criterion','fruits','4113',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_Regent','fruits','4114',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_Criterion','fruits','4115',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_Early','fruits','4116',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_Early','fruits','4117',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_Early','fruits','4118',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_Early','fruits','4119',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_Fiesta','fruits','4120',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_Elstar','fruits','4121',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_Sciros','fruits','4122',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_Elstar','fruits','4123',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_Empire','fruits','4124',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_Empire','fruits','4125',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_Empire','fruits','4126',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_Empire','fruits','4127',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_Cripps Pink','fruits','4128',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_Fuji','fruits','4129',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_Cripps Pink','fruits','4130',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_Fuji','fruits','4131',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_Gala','fruits','4132',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_Gala','fruits','4133',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_Gala','fruits','4134',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_Gala','fruits','4135',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_Golden Delicious','fruits','4136',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_Golden Delicious','fruits','4137',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_Granny Smith','fruits','4138',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_Granny Smith','fruits','4139',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_Idared','fruits','4140',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_Jonamac','fruits','4141',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_Idared','fruits','4142',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_Jonamac','fruits','4143',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_Jonagold','fruits','4144',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_Jonagold','fruits','4145',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_Jonagold','fruits','4146',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_Jonagold','fruits','4147',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_Jonathan','fruits','4148',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_Jonathan','fruits','4149',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_Jonathan','fruits','4150',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_Jonathan','fruits','4151',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_McIntosh','fruits','4152',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_McIntosh','fruits','4153',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_McIntosh','fruits','4154',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_Paulared','fruits','4155',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_Gravenstein','fruits','4156',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_Paulared','fruits','4157',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_Gravenstein','fruits','4158',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('ONIONS_Vidalia','vegetables','4159',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_Pippin','fruits','4160',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('ONIONS_Texas Sweet','vegetables','4161',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_Pippin','fruits','4162',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('ONIONS_Walla Walla','vegetables','4163',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('ONIONS_Maui','vegetables','4164',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('ONIONS_California Sweet','vegetables','4165',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('ONIONS_Other Sweet','vegetables','4166',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_Red Delicious','fruits','4167',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_Red Delicious','fruits','4168',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_Rome','fruits','4169',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_Rome','fruits','4170',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_Rome','fruits','4171',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_Rome','fruits','4172',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_Royal Gala','fruits','4173',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_Royal Gala','fruits','4174',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_Southern Snap','fruits','4176',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_Spartan','fruits','4177',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_Spartan','fruits','4178',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_Spartan','fruits','4179',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_Spartan','fruits','4180',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_Stayman','fruits','4181',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_Sturmer Pippin','fruits','4182',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_Stayman','fruits','4183',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_York','fruits','4185',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('BANANAS_Yellow (includes Cavendish)','fruits','4186',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_York','fruits','4187',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('NECTARINE_White Flesh, Tree Ripened, Ready-to-eat','fruits','4188',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_Winesap','fruits','4189',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_Winesap','fruits','4190',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_Winesap','fruits','4191',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLES_Winesap','fruits','4192',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APRICOTS_Regular','fruits','4218',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('ATEMOYAS_','fruits','4220',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('AVOCADOS_Green','fruits','4221',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('AVOCADOS_Green','fruits','4222',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('AVOCADOS_Green','fruits','4223',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('AVOCADOS_Green','fruits','4224',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('AVOCADOS_Hass','fruits','4225',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('AVOCADOS_Cocktail/Seedless','fruits','4226',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('BANANAS_Burro','fruits','4229',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('BANANAS_Dominique','fruits','4230',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('BANANAS_Green','fruits','4231',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('BANANAS_Leaves','fruits','4232',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('BANANAS_Apple/Manzano','fruits','4233',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('BANANAS_baby/Nino','fruits','4234',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('BANANAS_Plantain/Macho','fruits','4235',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('BANANAS_Red','fruits','4236',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('BERRIES_Blackberries','fruits','4239',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('BERRIES_Blueberries','fruits','4240',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('BERRIES_Boysenberries','fruits','4241',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('BERRIES_Cranberries','fruits','4242',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('BERRIES_Gooseberries','fruits','4243',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('BERRIES_Raspberries - Black','fruits','4244',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('BERRIES_Raspberries - Golden','fruits','4245',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('BERRIES_Strawberries','fruits','4246',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('BERRIES_Strawberries','fruits','4247',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('BERRIES_Strawberries','fruits','4248',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('BERRIES_Strawberries','fruits','4249',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('BERRIES_Strawberries','fruits','4250',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('BERRIES_Long-stemmed Strawberries','fruits','4251',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('BREADFRUIT_','fruits','4254',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('CACTUS PEAR (PRICKLY PEAR)_','fruits','4255',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('CARAMBOLA (STARFRUIT)_','fruits','4256',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('CHERIMOYA_','fruits','4257',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('CHERRIES_Golden/Rainier/White','fruits','4258',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('COCONUTS_In Husk/Waternut','fruits','4260',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('COCONUTS_Husked','fruits','4261',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('DATES_Fresh - Regular','fruits','4263',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('FEIJOA_','fruits','4265',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('FIGS_Black','fruits','4266',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('FIGS_Brown','fruits','4267',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('FIGS_White/Green','fruits','4268',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('GRAPES_Blue/Black Seeded (Ribier/Exotic/Niabel)','fruits','4270',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('GRAPES_Champagne','fruits','4271',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('GRAPES_Concord','fruits','4272',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('GRAPES_Red Seeded (Cardinal/Emperor/Queen/Christmas Rose)','fruits','4273',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('GRAPES_White/Green Seeded (All others not listed)','fruits','4274',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('GRAPEFRUIT_Pummelo - White','fruits','4279',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('GRAPEFRUIT_Ruby/Red/Pink (Includes Ray Ruby, Ray, Ruby Red)','fruits','4280',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('GRAPEFRUIT_Ruby/Red/Pink (ncludes Ray Ruby, Ruby, Ruby Red)','fruits','4281',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('GRAPEFRUIT_Ruby/Red/Pink (Includes Ray Ruby, Ruby, Ruby Red)','fruits','4282',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('GRAPEFRUIT_Ruby/Red/Pink (Includes Ray Ruby, Ray, Ruby Red)','fruits','4283',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('GRAPEFRUIT_Deep Red','fruits','4284',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('GRAPEFRUIT_Deep Red','fruits','4285',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('GRAPEFRUIT_Deep Red','fruits','4286',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('GRAPEFRUIT_Deep Red','fruits','4287',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('GRAPEFRUIT_Deep Red','fruits','4288',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('GRAPEFRUIT_Deep Red','fruits','4289',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('GRAPEFRUIT_White','fruits','4290',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('GRAPEFRUIT_White','fruits','4291',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('GRAPEFRUIT_White','fruits','4292',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('GRAPEFRUIT_White','fruits','4293',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('GRAPEFRUIT_White','fruits','4294',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('GRAPEFRUIT_White','fruits','4295',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('GUAVA_','fruits','4299',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('HOMLI FRUIT_','fruits','4300',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('KIWANO (HORNED MELON)_','fruits','4302',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('KUMQUAT_','fruits','4303',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('LIMES_Key (incl. Mexican & West Indian)','fruits','4305',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('LONGAN_','fruits','4307',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('LOQUATS_','fruits','4308',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('LYCHEES_','fruits','4309',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('MAMEY_','fruits','4310',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('MANGO_Green (Includes Keitt and Francis)','fruits','4311',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('MANGO_Yellow (Includes Oro, Ataulfo/Honey Manila)','fruits','4312',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('MELON_Canary/Yellow Honeydew','fruits','4317',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('MELON_Cantaloupe/Muskmelon','fruits','4318',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('MELON_Cantaloupe/Muskmelon','fruits','4319',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('MELON_Casaba','fruits','4320',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('MELON_Cinnabar','fruits','4321',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('MELON_Crenshaw','fruits','4322',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('BERRIES_Strawberries','fruits','4323',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('MELON_French Afternoon','fruits','4324',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('MELON_French Breakfast','fruits','4325',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('MELON_Galia','fruits','4326',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('MELON_Orange Flesh/Cantaline','fruits','4327',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('LIMEQUATS_','fruits','4328',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('MELON_Honeydew/White Honeydew','fruits','4329',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('MELON_Mayan','fruits','4330',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('MELON_Mickey Lee Watermelon/Sugarbaby','fruits','4331',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('MELON_Muskmelon','fruits','4332',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('MELON_Pepino','fruits','4333',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('MELON_Persian','fruits','4334',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('MELON_Prince','fruits','4335',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('MELON_Santa Claus','fruits','4336',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('MELON_Saticoy','fruits','4337',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('MELON_Sharlin','fruits','4338',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('MELON_Spanish/Tendral','fruits','4339',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('MELON_Watermelon - Yellow','fruits','4340',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('MELON_Watermelon - Yellow, Seedless','fruits','4341',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('NECTARINE_Yellow Flesh, Tree Ripened, Ready-to-eat','fruits','4377',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('NECTARINE_Yellow Flesh, Tree Ripened, Ready-to-eat','fruits','4378',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('ORANGES_Blood','fruits','4381',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('ORANGES_Juice','fruits','4382',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('TANGELO_Minneola','fruits','4383',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('ORANGES_Navel','fruits','4384',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('ORANGES_Navel','fruits','4385',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('ORANGES_Temple','fruits','4386',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('ORANGES_Temple','fruits','4387',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('ORANGES_Valencia','fruits','4388',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('PAPAYA/PAWPAW_Regular','fruits','4394',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('PAPAYA/PAWPAW_Cooking/Mexican','fruits','4395',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('PASSION FRUIT_Purple','fruits','4397',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('PEACHES_Indian','fruits','4399',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('PEACHES_White Flesh','fruits','4400',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('PEACHES_White Flesh','fruits','4401',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('PEACHES_Yellow Flesh','fruits','4402',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('PEACHES_Yellow Flesh','fruits','4403',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('PEARS_Asian/Nashi - White','fruits','4406',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('PEARS_Asian/Nashi - Yellow','fruits','4407',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('PEARS_Asian/Nashi - Brown','fruits','4408',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('PEARS_Bartlett/Williams/WBC','fruits','4409',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('PEARS_Bartlett - Red/Red Sensation','fruits','4410',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('PEARS_Bosc/Beurre Bosc','fruits','4411',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('PEARS_Bosc/Beurre Bosc','fruits','4412',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('PEARS_Bosc/Beurre Bosc','fruits','4413',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('PEARS_Comice/ Doyenne du Comice','fruits','4414',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('PEARS_Red','fruits','4415',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('PEARS_Anjou','fruits','4416',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('PEARS_Anjou - Red','fruits','4417',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('PEARS_Forelle/Corella','fruits','4418',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('PEARS_French','fruits','4419',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('PEARS_King Royal','fruits','4420',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('PEARS_Packham/Packhams Triumph','fruits','4421',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('PEARS_Seckel','fruits','4422',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('PEARS_Tree Ripened','fruits','4423',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('PEARS_Winter Nelis/Honey','fruits','4424',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('PERSIMMON_Regular (American Persimmon)','fruits','4427',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('PERSIMMON_Japanese/Sharonfruit (Kaki)','fruits','4428',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('PINEAPPLE_','fruits','4430',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('PINEAPPLE_Jet Fresh','fruits','4431',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('PINEAPPLE_Jet Fresh','fruits','4432',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('PLUMS_Green (Includes Dolly, Kelsey, Wickson)','fruits','4434',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('PLUMS_Green (Includes Dolly, Kelsey, Wickson)','fruits','4435',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('PLUMS_Italian Prune/Sugar','fruits','4436',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('PLUMS_Purple (Includes Queen Rosa, Laroda, Nublana, Queen Ann, Simka, El Dorado)','fruits','4437',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('PLUMS_Purple (Includes Queen Rosa, Laroda, Nublana, Queen Ann, Simka, El Dorado) ','fruits','4438',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('PLUMS_Tree Ripened','fruits','4439',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('PLUMS_Tree Ripened','fruits','4440',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('PLUMS_Yellow (Includes Golden Globe)','fruits','4441',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('PLUMS_Yellow (Includes Golden Globe)','fruits','4442',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('POMEGRANATE_','fruits','4445',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('QUINCE_','fruits','4447',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('TAMARIND_','fruits','4448',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('TANGERINES/MANDARINS_Sunburst','fruits','4449',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('TANGERINES/MANDARINS_Clementine (includes Fortune)','fruits','4450',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('TANGERINES/MANDARINS_Dancy','fruits','4451',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('TANGERINES/MANDARINS_Fairchild','fruits','4452',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('TANGERINES/MANDARINS_Honey/Murcott','fruits','4453',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('TANGERINES/MANDARINS_Kinnow','fruits','4454',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('TANGERINES/MANDARINS_Mandarin/Royal','fruits','4455',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('TANGELO_','fruits','4456',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('TANGELO_Jamaican','fruits','4459',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('SALAD BAR_','fruits','4470',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('GRAPEFRUIT_Ruby/Red/Pink (includes Ray Ruby, Ruby, Ruby Red)','fruits','4491',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('GRAPEFRUIT_Ruby/Red/Pink (includes Ray Ruby, Ruby, Ruby Red)','fruits','4492',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('GRAPEFRUIT_Ruby/Red/Pink (Includes Ray Ruby, Ruby, Ruby Red)','fruits','4493',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('GRAPEFRUIT_Deep Red','fruits','4494',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('GRAPEFRUIT_Deep Red','fruits','4495',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('GRAPEFRUIT_Deep Red','fruits','4496',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('GRAPES_Sugraone','fruits','4497',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('GRAPES_White/Green Seedless (All others not listed above (including Autumn King))','fruits','4498',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('GRAPES_Crimson/Majestic','fruits','4499',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('ALFALFA SPROUTS_','vegetables','4514',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('FENNEL_Florence/Sweet Fennel/Fennel Bulb','herbs','4515',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('ARTICHOKES_','vegetables','4516',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('ARTICHOKES_Purple','vegetables','4517',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('ARTICHOKES_Purple','vegetables','4518',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('ARTICHOKES_Baby/Cocktail','vegetables','4519',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('ASPARAGUS_Green','vegetables','4521',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('ASPARAGUS_White','vegetables','4522',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('ASPARAGUS_White','vegetables','4523',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('ASPARAGUS_Tips','vegetables','4524',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('BEANS_Chinese Long/Snake','vegetables','4527',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('BEANS_Fava/Broad','vegetables','4528',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('BEANS_Lima','vegetables','4529',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('BEANS_Pole/Runner/Stick','vegetables','4530',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('BEANS_Purple Hull','vegetables','4531',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('BEANS_Shell','vegetables','4532',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('BEANS_Wax/Yellow','vegetables','4533',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('BEANS_Winged','vegetables','4534',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('BEAN SPROUTS_Mung Bean Sprouts','vegetables','4536',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('BEETS_Baby Golden','vegetables','4537',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('BEETS_Baby Red','vegetables','4538',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('BEETS_Bunch','vegetables','4539',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('BEETS_Loose','vegetables','4540',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('BEET GREENS_','vegetables','4542',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('BELGIAN ENDIVE (WITLOOF CHICORY)_','vegetables','4543',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('BOK CHOY (PAK CHOI)_Small/Baby','vegetables','4544',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('BOK CHOY (PAK CHOI)_','vegetables','4545',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('BONIATO_See also SWEET POTATO','vegetables','4546',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('BROCCOLI_Broccoli Rabe (Italian Rapini)/ Chinese Broccoli (GAI LAN)','vegetables','4547',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('BROCCOLI_Florettes','vegetables','4548',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('BRUSSELS SPROUTS_','vegetables','4550',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('CABBAGE_Chinese/Napa/Wong Bok','vegetables','4552',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('PEARS_Taylors Gold','fruits','4553',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('CABBAGE_Red','vegetables','4554',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('CABBAGE_Savoy, Green','vegetables','4555',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('CACTUS LEAVES (Nopales/Cactus Pads)_','vegetables','4558',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('CARDOON (CARDONI)_','vegetables','4559',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('CARROTS_Baby','vegetables','4560',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('CARROTS_French','vegetables','4561',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('CARROTS_Loose','vegetables','4562',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('CARROTS_Carrot Sticks','vegetables','4563',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('CAULIFLOWER_Florettes','vegetables','4566',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('CAULIFLOWER_Green','vegetables','4567',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('CAULIFLOWER_Purple','vegetables','4568',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('CAULIFLOWER_','vegetables','4572',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('CAULIFLOWER_Baby','vegetables','4573',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('CELERY_Hearts','vegetables','4575',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('CELERY_Celery Sticks','vegetables','4576',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('CELERY_Bunch','vegetables','4582',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('CELERY_Bunch','vegetables','4583',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('MANGO_Green (Includes Keitt and Francis)','fruits','4584',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('CELERY ROOT/CELERIAC_','vegetables','4585',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('CHARD (SWISS CHARD)/SILVERBEET_Green','vegetables','4586',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('CHARD (SWISS CHARD)/SILVERBEET_Red','vegetables','4587',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('CORN_Sweet Corn, Baby','vegetables','4589',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('CORN_Sweet Corn, Bi-Color','vegetables','4590',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('CUCUMBER_Armenian','vegetables','4592',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('CUCUMBER_English/Hot House/Long Seedless/Telegraph/Continental','vegetables','4593',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('CUCUMBER_Japanese/White','vegetables','4594',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('CUCUMBER_Lemon','vegetables','4595',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('CUCUMBER_Pickling/Gherkin','vegetables','4596',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('DAIKON_(See also RADISH)','vegetables','4598',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('EGGPLANT (AUBERGINE)_Baby','vegetables','4599',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('EGGPLANT (AUBERGINE)_Baby White','vegetables','4600',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('EGGPLANT (AUBERGINE)_Japanese','vegetables','4601',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('EGGPLANT (AUBERGINE)_White','vegetables','4602',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('ENDIVE/CHICORY_','vegetables','4604',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('ESCAROLE/BATAVIAN CHICORY_Green','vegetables','4605',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('FIDDLEHEAD FERNS_','vegetables','4606',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('GAI (GUI) CHOY (CHINESE or INDIAN MUSTARD)_Chinese or Indian Mustard','vegetables','4607',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('GARLIC_Regular','vegetables','4608',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('GARLIC_Elephant','vegetables','4609',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('GINGER ROOT_Regular','vegetables','4612',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('GREENS_Collard','vegetables','4614',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('GREENS_Dandelion','vegetables','4615',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('GREENS_Mustard (Synonymous with Gai (Gui) Choy)','vegetables','4616',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('GREENS_Polk Greens','vegetables','4617',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('GREENS_Texas Mustard','vegetables','4618',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('GREENS_Turnip','vegetables','4619',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('HORSERADISH ROOT_','vegetables','4625',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('JICAMA/YAM BEAN_','vegetables','4626',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('KALE_','vegetables','4627',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('KOHLRABI_','vegetables','4628',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('LEEKS_Regular','vegetables','4629',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('LEEKS_Baby','vegetables','4630',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('LETTUCE_Bibb/Flat/Round','vegetables','4631',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('LETTUCE_Boston/Butter','vegetables','4632',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('LETTUCE_Hydroponic','vegetables','4633',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('LETTUCE_Iceberg','vegetables','4634',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('GRAPES_Red Seedless (All others not listed under red seedless)','fruits','4635',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('GRAPES_Red Globe','fruits','4636',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('GRAPES_Red Seeded (All others not listed above)','fruits','4637',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('GRAPES_Fantasy/Marroo','fruits','4638',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('LETTUCE_Mache','vegetables','4639',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('LETTUCE_Romaine/Cos','vegetables','4640',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('MALANGA_','vegetables','4644',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('MUSHROOMS_Regular, Button','vegetables','4645',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('MUSHROOMS_Black Forest','vegetables','4646',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('MUSHROOMS_Chanterelle','vegetables','4647',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('MUSHROOMS_Cremini/Brown/Swiss Brown','vegetables','4648',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('MUSHROOMS_Oyster','vegetables','4649',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('MUSHROOMS_Portabella (Synonymous with Cremini, Brown, Swiss Brown Mushrooms)','vegetables','4650',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('MUSHROOMS_Shiitake','vegetables','4651',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('MUSHROOMS_Wood Ear','vegetables','4652',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('OKRA_Regular (Green)','vegetables','4655',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('OKRA_Chinese','vegetables','4656',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('OKRA_Red','vegetables','4657',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('ONIONS_Boiling','vegetables','4658',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('ONIONS_Bulb','vegetables','4659',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('ONIONS_Pearl','vegetables','4660',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('ONIONS_Pickling, White','vegetables','4661',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('ONIONS_Shallots','vegetables','4662',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('ONIONS_White','vegetables','4663',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('TOMATOES_Regular - Red, On the Vine (Truss)','vegetables','4664',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('ONIONS_Yellow/Brown','vegetables','4665',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('PARSLEY ROOT(HAMBURG PARSLEY)_','vegetables','4671',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('PARSNIP_','vegetables','4672',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('PEAS_Blackeyed','vegetables','4673',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('PEAS_Green','vegetables','4674',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('PEAS_Sugar Snap','vegetables','4675',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('PEPPERS (CAPSICUMS)_Anaheim (Green and Red)','vegetables','4677',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('PEPPERS (CAPSICUMS)_Banana (Yellow Long)','vegetables','4678',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('PEPPERS (CAPSICUMS)_Bell, Field Grown - Brown','vegetables','4679',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('PEPPERS (CAPSICUMS)_Bell, Field Grown - Golden (Yellow)','vegetables','4680',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('PEPPERS (CAPSICUMS)_Bell, Field Grown - Green','vegetables','4681',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('PEPPERS (CAPSICUMS)_Bell, Field Grown - Orange','vegetables','4682',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('PEPPERS (CAPSICUMS)_Bell, Field Grown - Purple','vegetables','4683',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('PEPPERS (CAPSICUMS)_Bell, Field Grown - White','vegetables','4684',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('PEPPERS (CAPSICUMS)_Chili - Dried','vegetables','4685',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('PEPPERS (CAPSICUMS)_Chili - Green','vegetables','4686',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('PEPPERS (CAPSICUMS)_Cubanelle','vegetables','4687',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('PEPPERS (CAPSICUMS)_Bell, Greenhouse - Red','vegetables','4688',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('PEPPERS (CAPSICUMS)_Bell, Greenhouse - Yellow','vegetables','4689',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('PEPPERS (CAPSICUMS)_Hot (Hungarian Hot)','vegetables','4690',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('PEPPERS (CAPSICUMS)_Hot Mixed','vegetables','4691',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('PEPPERS (CAPSICUMS)_Hungarian Wax','vegetables','4692',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('PEPPERS (CAPSICUMS)_Jalapeno - Green/Mexican Green','vegetables','4693',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('PEPPERS (CAPSICUMS)_Jalapeno - Red/Mexican Red','vegetables','4694',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('PEPPERS (CAPSICUMS)_Japanese - Red','vegetables','4695',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('PEPPERS (CAPSICUMS)_Long Hot - Green','vegetables','4696',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('PEPPERS (CAPSICUMS)_Long Hot - Red','vegetables','4697',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('PEPPERS (CAPSICUMS)_Morita Chili','vegetables','4698',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('PEPPERS (CAPSICUMS)_Negro','vegetables','4699',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('PEPPERS (CAPSICUMS)_New Mexico','vegetables','4700',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('PEPPERS (CAPSICUMS)_Pasilla - Green','vegetables','4701',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('PEPPERS (CAPSICUMS)_Pasilla - Red','vegetables','4702',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('PEPPERS (CAPSICUMS)_Pasilla Pod','vegetables','4703',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('PEPPERS (CAPSICUMS)_Pinole','vegetables','4704',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('PEPPERS (CAPSICUMS)_Poblano','vegetables','4705',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('PEPPERS (CAPSICUMS)_Red Cheese','vegetables','4706',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('PEPPERS (CAPSICUMS)_Red Finger','vegetables','4707',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('PEPPERS (CAPSICUMS)_Red Pimiento/ Red Sweet Long','vegetables','4708',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('PEPPERS (CAPSICUMS)_Serrano','vegetables','4709',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('POTATO_Creamer - Red','vegetables','4723',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('POTATO_Creamer - White','vegetables','4724',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('POTATO_Russet','vegetables','4725',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('POTATO_Long - White','vegetables','4726',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('POTATO_Yellow','vegetables','4727',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('PUMPKIN_Mini','vegetables','4734',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('PUMPKIN_Regular','vegetables','4735',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('RADICCHIO_','vegetables','4738',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('RADISH_Black','vegetables','4739',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('RADISH_Bunched White','vegetables','4740',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('RADISH_Italian Red','vegetables','4741',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('RADISH_Red','vegetables','4742',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('RADISH_White/Icicle','vegetables','4743',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('RHUBARB_Regular','vegetables','4745',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('RUTABAGAS (SWEDE)_Regular','vegetables','4747',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('SQUASH_Acorn/Table Queen','vegetables','4750',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('SQUASH_Acorn - Golden','vegetables','4751',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('SQUASH_Acorn - Swan White Table Queen','vegetables','4752',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('SQUASH_Australian Blue','vegetables','4753',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('SQUASH_Baby Scallopini','vegetables','4754',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('SQUASH_Baby Summer (Green)','vegetables','4755',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('SQUASH_Baby Green Zucchini/Courgette','vegetables','4756',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('SQUASH_Banana','vegetables','4757',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('SQUASH_Buttercup','vegetables','4758',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('SQUASH_Butternut','vegetables','4759',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('SQUASH_Calabaza','vegetables','4760',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('SQUASH_Chayote/Choko','vegetables','4761',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('ARTICHOKES_','vegetables','4762',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('SQUASH_Delicata/Sweet Potato','vegetables','4763',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('SQUASH_(Sweet) Dumpling','vegetables','4764',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('SQUASH_Gem','vegetables','4765',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('SQUASH_Golden Delicious','vegetables','4766',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('SQUASH_Golden Nugget','vegetables','4767',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('SQUASH_Hubbard','vegetables','4768',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('SQUASH_Kabocha','vegetables','4769',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('AVOCADOS_Hass','fruits','4770',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('AVOCADOS_Green','fruits','4771',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('PEPPERS (CAPSICUMS)_Chili - Yellow','vegetables','4772',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('SQUASH_Patty Pan/Summer','vegetables','4773',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('SQUASH_Red Kuri','vegetables','4774',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('SQUASH_Scallopini','vegetables','4775',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('SQUASH_Spaghetti/Vegetable Spaghetti','vegetables','4776',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('SQUASH_Sunburst (Yellow)','vegetables','4777',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('TOMATOES_Regular - Yellow','vegetables','4778',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('SQUASH_Sweet Mama','vegetables','4779',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('SQUASH_Turban','vegetables','4780',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('SQUASH_White','vegetables','4781',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('SQUASH_Yellow - Straightneck','vegetables','4782',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('BITTER MELON/BITTER GOURD, Foo Qua_Foo Qua','vegetables','4783',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('SQUASH_Yellow - Crookneck','vegetables','4784',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('SUGAR CANE_','vegetables','4790',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('SUNCHOKES (JERUSALEM ARTICHOKES)_','vegetables','4791',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('TAMARILLO_Golden','vegetables','4792',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('TAMARILLO_Red','vegetables','4793',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('TARO ROOT (DASHEEN)_','vegetables','4794',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('TARO ROOT (DASHEEN)_','vegetables','4795',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('TOMATOES_Cherry - Red','vegetables','4796',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('TOMATOES_Cherry - Yellow','vegetables','4797',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('TOMATOES_Greenhouse/Hydroponic/Regular - Red','vegetables','4798',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('TOMATOES_Greenhouse/Hydroponic/Regular - Red','vegetables','4799',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('TOMATOES_Native/Home Grown','vegetables','4800',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('TOMATOES_Tomatillos/Husk Tomatoes','vegetables','4801',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('TOMATOES_Dried','vegetables','4802',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('TOMATOES_Teardrop/Pear - Red','vegetables','4803',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('TOMATOES_Teardrop/Pear - Yellow','vegetables','4804',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('TOMATOES_Vine Ripe, Regular - Red','vegetables','4805',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('TURNIP_Baby','vegetables','4809',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('TURNIP_Bunch/Banded','vegetables','4810',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('TURNIP_Purple Top','vegetables','4811',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('TURNIP_White','vegetables','4812',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('WATER CHESTNUTS_','vegetables','4814',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('WATERCRESS_','vegetables','4815',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('SWEET POTATO/YAM/KUMARA_Golden','vegetables','4816',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('SWEET POTATO/YAM/KUMARA_Red/Orangy Red Flesh','vegetables','4817',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('YUCA ROOT/CASSAVA/MANIOC_','vegetables','4819',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APPLE SLICES_Dried ','dried fruits','4860',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('APRICOTS_Dried','dried fruits','4861',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('DATES_Dried','dried fruits','4862',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('PINEAPPLE_Dried','dried fruits','4864',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('PRUNES_Regular (Dried Fruit)','dried fruits','4865',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('PRUNES_Pitted (Dried Fruit)','dried fruits','4866',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('RAISINS_Black (Dried Fruit)','dried fruits','4868',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('RAISINS_Golden/Yellow (Dried Fruit)','dried fruits','4869',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('ARUGULA/ROCKET_','herbs','4884',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('BASIL_','herbs','4885',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('BASIL_Opal','herbs','4886',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('BASIL_Sweet','herbs','4887',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('CHIVES_','herbs','4888',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('CILANTRO (CHINESE PARSLEY/CORIANDER)_','herbs','4889',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('PEARS_Chinese Yali','fruits','4890',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('DILL_','herbs','4891',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('DILL_Baby','herbs','4892',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('DILL_Pickling','herbs','4893',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('LEMONGRASS_','herbs','4894',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('MARJORAM_','herbs','4895',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('MINT_','herbs','4896',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('OREGANO_','herbs','4897',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('OYSTER PLANT/SALSIFY_','herbs','4898',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('PARSLEY_Regular/Curly','herbs','4899',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('PARSLEY_Italian/Continental/French','herbs','4901',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('ROSEMARY_','herbs','4903',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('SAGE_','herbs','4904',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('SORREL_','herbs','4905',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('TARRAGON_','herbs','4906',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('THYME_','herbs','4907',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('VANILLA BEAN_','herbs','4908',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('ALMONDS_','nuts','4924',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('BRAZILNUTS_','nuts','4926',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('CHESTNUTS_','nuts','4927',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('FILBERTS_Cobnut/Hazelnut','nuts','4928',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('MIXED NUTS_','nuts','4929',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('PEANUTS_','nuts','4930',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('PEANUTS_Raw','nuts','4931',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('PEANUTS_Roasted - Salted','nuts','4932',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('PEANUTS_Roasted - Unsalted','nuts','4933',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('PECANS_','nuts','4936',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('PINE NUTS (PIGNOLI)_','nuts','4938',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('PISTACHIO_Natural','nuts','4939',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('PISTACHIO_Red','nuts','4940',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('SUNFLOWER SEEDS_','nuts','4942',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('WALNUTS_Regular','nuts','4943',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('WALNUTS_Black','nuts','4944',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('WALNUTS_White','nuts','4945',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('GRAPES_Blue/Black Seeded (All others not listed above)','fruits','4957',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('LEMONS_','fruits','4958',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('MANGO_Red (Includes Tommy Atkins, Kent, Palmer Vandyke, Edward, Hayden)','fruits','4959',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('PEARS_Fragrant','fruits','4960',(SELECT MAX(stor_id) FROM Storage_type)-1,1),
('MANGO_Yellow','fruits','4961',(SELECT MAX(stor_id) FROM Storage_type)-1,1);