name: Coverage Report

on:
  pull_request:
    branches: [main , frontend_testing]

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: |
          cd backend
          npm install --save-dev typescript-coverage-report
      - name: Generate coverage report
        run: |
          cd backend
          npm run ts-coverage
  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: |
          cd frontend
          npm install
      - name: Generate coverage report
        run: |
          cd frontend
          npm run coverage
