# name: Coverage Report

# on:
#   pull_request:
#     branches: [main , frontend_testing]

# jobs:
#   backend:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3
#       - uses: actions/setup-node@v3
#         with:
#           node-version: 16
#       - name: Install dependencies
#         run: |
#           cd backend
#           npm install --save-dev typescript-coverage-report
#       - name: Generate coverage report
#         run: |
#           cd backend
#           npm run ts-coverage
#   frontend:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3
#       - uses: actions/setup-node@v3
#         with:
#           node-version: 16
#       - name: Install dependencies
#         run: |
#           cd frontend
#           npm install
#       - name: Generate coverage report
#         run: |
#           cd frontend
#           npm run coverage

name: Code Coverage and Badge Update

on:
  pull_request:
    types:
      - opened
      - synchronize
  push:
    branches:
      - main

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm ci

      - name: Run tests with coverage
        run: npm test -- --coverage

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: ./coverage

  update-readme-badge:
    needs: coverage
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm ci

      - name: Update README.md coverage badge
        run: |
          # Update the command if your coverage badge needs a different format
          sed -i 's/coverage-badge-placeholder/![Coverage](https:\/\/img.shields.io\/badge\/coverage-{{INSERT_CURRENT_COVERAGE_PERCENTAGE}}-green)/' README.md

      - name: Commit changes to README.md
        run: |
          git config --global user.name "Your Name"
          git config --global user.email "your-email@example.com"
          git add README.md
          git commit -m "Update coverage badge [skip ci]"
          git push